# Generated by Django 5.2.15 on 2026-06-12 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeownerprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='availability',
            field=models.CharField(choices=[('full', 'Full-time'), ('part', 'Part-time')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='licensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='primary_trade',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='response_hours',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='service_center_zip',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='service_mode',
            field=models.CharField(choices=[('explicit', 'Specific ZIPs'), ('radial', 'Center + radius')], default='explicit', max_length=10),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='skill_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='wallpaper_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=40)),
                ('line1', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.homeownerprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_alerts', models.BooleanField(default=True)),
                ('whatsapp_dispatch', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pros', to='accounts.homeownerprofile')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='accounts.proprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('homeowner', 'pro'), name='unique_saved_pro')],
            },
        ),
    ]
