# Generated by Django 5.2.15 on 2026-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_homeownerprofile_avatar_url_proprofile_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprofile',
            name='handle',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
