# Generated by Django 5.2.15 on 2026-06-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_pro_handles'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprofile',
            name='wallpaper_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
