# Generated by Django 5.2.15 on 2026-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_gk_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprofile',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
