# Generated by Django 5.2.15 on 2026-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_waitlistentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kraftclick',
            new_name='accounts_kr_pro_id_9bb90a_idx',
            old_name='accounts_kc_pro_id_creat_idx',
        ),
        migrations.RenameIndex(
            model_name='kraftclick',
            new_name='accounts_kr_kraft_i_24baf1_idx',
            old_name='accounts_kc_kraft_id_creat_idx',
        ),
        migrations.RenameIndex(
            model_name='kraftimpression',
            new_name='accounts_kr_pro_id_51a948_idx',
            old_name='accounts_ki_pro_id_creat_idx',
        ),
        migrations.RenameIndex(
            model_name='kraftimpression',
            new_name='accounts_kr_kraft_i_8a7355_idx',
            old_name='accounts_ki_kraft_id_creat_idx',
        ),
        migrations.RenameIndex(
            model_name='proprofileview',
            new_name='accounts_pr_pro_id_42a687_idx',
            old_name='accounts_pr_pro_id_creat_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('pro', 'Pro'), ('homeowner', 'Homeowner'), ('node_manager', 'Node Manager'), ('gk_admin', 'GK Admin')], max_length=20),
        ),
    ]
