# Generated by Django 5.2.15 on 2026-06-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
