# Generated by Django 5.2.15 on 2026-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_favoritepro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('member', 'Member'), ('pro', 'Pro'), ('homeowner', 'Homeowner'), ('referrer', 'Referrer'), ('node_manager', 'Node Manager'), ('gk_admin', 'GK Admin')], max_length=20),
        ),
    ]
