# Generated by Django 5.2.15 on 2026-07-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_homeownerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('member', 'Member'), ('pro', 'Pro'), ('homeowner', 'Homeowner'), ('referrer', 'Referrer'), ('community_lead', 'Community Lead'), ('node_manager', 'Node Manager'), ('gk_admin', 'GK Admin')], max_length=20),
        ),
    ]
