# Generated by Django 5.2.15 on 2026-07-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_backfill_user_phone_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
