# Generated by Django 5.2.15 on 2026-07-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprofile',
            name='communication_quality_pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='metrics_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='popularity_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='pricing_transparency_pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='professionalism_cleanliness_pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='quality_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='recommended_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='rehire_intent_pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='schedule_adherence_pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
