# Generated by Django 5.2.15 on 2026-06-25 15:26

import django.db.models.deletion
import referrals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trade', models.CharField(max_length=60)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('note', models.TextField(blank=True, default='')),
                ('token', models.CharField(db_index=True, default=referrals.models._generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_pro_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferrerFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('cookie_token', models.CharField(db_index=True, max_length=64)),
                ('phone_verified', models.BooleanField(default=False)),
                ('referrals_received', models.PositiveIntegerField(default=0)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following_referrers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('otp_pending', 'OTP Pending'), ('sent', 'Sent'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('otp_code_hash', models.CharField(blank=True, default='', max_length=64)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pending_note_to_follower', models.TextField(blank=True, default='')),
                ('pending_note_to_pro', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='referrals.referrerfollower')),
            ],
        ),
        migrations.CreateModel(
            name='FriendInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('followed_at', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_friend_invite', to='referrals.referrerfollower')),
            ],
        ),
        migrations.CreateModel(
            name='ReferrerPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement', models.CharField(blank=True, default='', max_length=200)),
                ('show_on_page', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_memberships', to='accounts.proprofile')),
                ('pro_invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_pro', to='referrals.proinvite')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_pros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_to_follower', models.TextField()),
                ('note_to_pro', models.TextField()),
                ('follower_sms_status', models.CharField(default='pending', max_length=20)),
                ('pro_sms_status', models.CharField(default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('referral_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='referrals.referralrequest')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received_records', to='referrals.referrerfollower')),
                ('referrer_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent', to='referrals.referrerpro')),
            ],
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='referrer_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='referrals.referrerpro'),
        ),
        migrations.CreateModel(
            name='ReferrerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('bio', models.CharField(blank=True, default='', max_length=160)),
                ('avatar_url', models.TextField(blank=True, default='')),
                ('default_zip', models.CharField(blank=True, default='', max_length=10)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=100)),
                ('raw_phone', models.CharField(blank=True, default='', max_length=20)),
                ('raw_email', models.EmailField(blank=True, default='', max_length=254)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('matched_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_matches', to='accounts.proprofile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='referrerfollower',
            index=models.Index(fields=['referrer', 'cookie_token'], name='referrals_r_referre_b3ecb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='referrerfollower',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('referrer', 'phone'), name='unique_referrer_follower_phone'),
        ),
        migrations.AddConstraint(
            model_name='referrerfollower',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('referrer', 'email'), name='unique_referrer_follower_email'),
        ),
        migrations.AddConstraint(
            model_name='referrerpro',
            constraint=models.UniqueConstraint(condition=models.Q(('pro__isnull', False)), fields=('referrer', 'pro'), name='unique_referrer_pro'),
        ),
        migrations.AddConstraint(
            model_name='referrerpro',
            constraint=models.UniqueConstraint(condition=models.Q(('pro_invite__isnull', False)), fields=('referrer', 'pro_invite'), name='unique_referrer_pro_invite'),
        ),
        migrations.AddConstraint(
            model_name='referralrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'otp_pending'])), fields=('referrer', 'follower', 'referrer_pro'), name='unique_active_request_per_pro'),
        ),
        migrations.AddIndex(
            model_name='referrerprofile',
            index=models.Index(fields=['slug'], name='referrals_r_slug_3c0552_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedcontact',
            index=models.Index(fields=['uploaded_by', 'is_active'], name='referrals_u_uploade_3e80f1_idx'),
        ),
    ]
