# Generated by Django 5.2.15 on 2026-06-26 17:41

import referrals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_invite_channel_click_friend_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvite',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proinvite',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friendinvite',
            name='token',
            field=models.CharField(db_index=True, default=referrals.models._generate_token, max_length=32, unique=True),
        ),
    ]
