# Generated by Django 5.2.15 on 2026-06-30 03:13

import django.db.models.deletion
import django.utils.timezone
import referrals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_invite_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvite',
            name='message_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proinvite',
            name='message_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CircleShareInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('channel', models.CharField(blank=True, default='', max_length=10)),
                ('message_body', models.TextField(blank=True, default='')),
                ('token', models.CharField(db_index=True, default=referrals.models._generate_token, max_length=32, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('last_resent_at', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_shares_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InviteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('pro', 'Pro'), ('friend', 'Friend'), ('circle', 'Circle')], max_length=10)),
                ('invite_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('resent', 'Resent'), ('clicked', 'Link Clicked'), ('joined', 'Joined / Claimed / Followed')], max_length=10)),
                ('message_body', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['scenario', 'invite_id'], name='referrals_i_scenari_9573e9_idx')],
            },
        ),
    ]
