# Generated by Django 5.2.15 on 2026-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_circle_share_invite_and_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleshareinvite',
            name='email_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circleshareinvite',
            name='email_track_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='friendinvite',
            name='email_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendinvite',
            name='email_track_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proinvite',
            name='email_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proinvite',
            name='email_track_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inviteevent',
            name='event_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('resent', 'Resent'), ('opened', 'Email Opened'), ('clicked', 'Link Clicked'), ('joined', 'Joined / Claimed / Followed')], max_length=10),
        ),
    ]
