# Generated by Django 5.2.15 on 2026-07-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_circleaddnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteevent',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
