# Generated by Django 5.2.15 on 2026-07-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_inviteevent_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleshareinvite',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friendinvite',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='proinvite',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='referrerfollower',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='uploadedcontact',
            name='raw_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
