# Generated by Django 5.2.15 on 2026-07-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0010_backfill_phone_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrerpro',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
