# Generated by Django 5.2.15 on 2026-07-15 00:31, hand-edited to backfill
# unique short codes before the unique constraint is enforced (a plain
# AddField with a blank default would collide across existing rows).
import secrets

from django.db import migrations, models

_SHORT_CODE_ALPHABET = "abcdefghijkmnpqrstuvwxyz23456789"


def _generate_short_code(length: int = 6) -> str:
    return "".join(secrets.choice(_SHORT_CODE_ALPHABET) for _ in range(length))


def backfill_short_codes(apps, schema_editor):
    ReferrerProfile = apps.get_model("referrals", "ReferrerProfile")
    existing = set(ReferrerProfile.objects.exclude(short_code="").values_list("short_code", flat=True))
    for profile in ReferrerProfile.objects.filter(short_code=""):
        code = _generate_short_code()
        while code in existing:
            code = _generate_short_code()
        existing.add(code)
        profile.short_code = code
        profile.save(update_fields=["short_code"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0011_referrerpro_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrerprofile',
            name='short_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='referrerprofile',
            name='short_link_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_short_codes, noop_reverse),
        migrations.AlterField(
            model_name='referrerprofile',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, unique=True),
        ),
    ]
