# Generated by Django, hand-edited to backfill unique short codes before the
# unique constraint is enforced (a plain AddField with a blank default would
# collide across existing rows) — mirrors 0012_referrerprofile_short_code_and_more.
import secrets

from django.db import migrations, models

_SHORT_CODE_ALPHABET = "abcdefghijkmnpqrstuvwxyz23456789"


def _generate_short_code(length: int = 6) -> str:
    return "".join(secrets.choice(_SHORT_CODE_ALPHABET) for _ in range(length))


def backfill_short_codes(apps, schema_editor):
    ReferrerPro = apps.get_model("referrals", "ReferrerPro")
    existing = set(ReferrerPro.objects.exclude(short_code="").values_list("short_code", flat=True))
    for rp in ReferrerPro.objects.filter(short_code=""):
        code = _generate_short_code()
        while code in existing:
            code = _generate_short_code()
        existing.add(code)
        rp.short_code = code
        rp.save(update_fields=["short_code"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0012_referrerprofile_short_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrerpro',
            name='short_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='referrerpro',
            name='short_link_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_short_codes, noop_reverse),
        migrations.AlterField(
            model_name='referrerpro',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, unique=True),
        ),
    ]
