# Generated by Django 5.2.15 on 2026-07-15 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('referrals', '0013_referrerpro_short_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrerpro',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pros', to='communities.community'),
        ),
        migrations.AddField(
            model_name='referrerpro',
            name='show_on_community',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inviteevent',
            name='scenario',
            field=models.CharField(choices=[('pro', 'Pro'), ('friend', 'Friend'), ('circle', 'Circle'), ('community_member', 'Community Member')], max_length=20),
        ),
    ]
