# Generated by Django 5.2.15 on 2026-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0014_referrerpro_community_referrerpro_show_on_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proinvite',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
