# Generated by Django 5.2.15 on 2026-07-17 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0016_referrerpro_communication_quality_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referrerpro',
            name='pending_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referrerpro',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_pro_recommendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
