# Generated by Django 5.2.15 on 2026-07-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0017_referrerpro_pending_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proinvite',
            name='url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
