# Generated by Django 5.2.15 on 2026-06-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('center_zip', models.CharField(blank=True, default='', max_length=10)),
                ('service_zips', models.JSONField(blank=True, default=list)),
                ('radius_miles', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['node_id'],
            },
        ),
    ]
