# Generated by Django 5.2.15 on 2026-06-12 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_homeownerprofile_avatar_url_proprofile_availability_and_more'),
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='auto_blast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='default_sla_hours',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='node',
            name='escalation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='escalation_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='node',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SafetyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infraction', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('suspended', 'Suspended')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_logs', to='nodes.node')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_logs', to='accounts.proprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
