# Generated by Django 5.2.15 on 2026-06-12 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_homeownerprofile_avatar_url_proprofile_availability_and_more'),
        ('leads', '0001_initial'),
        ('nodes', '0002_node_auto_blast_node_default_sla_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('burst', 'Burst pipe'), ('power', 'Power out'), ('hvac', 'HVAC down'), ('lock', 'Lockout'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('zip', models.CharField(blank=True, default='', max_length=10)),
                ('budget_ceiling', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('routed', 'Routed by admin'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_broadcasts', to='accounts.proprofile')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='leads.lead')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='nodes.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('notified', 'Notified'), ('claimed', 'Claimed')], default='notified', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='accounts.proprofile')),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergencies.emergencybroadcast')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
