# Generated by Django 5.2.15 on 2026-06-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_homeownerprofile_avatar_url_proprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('discount_pct', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Pro Vault Monthly'), ('annual', 'Pro Vault Annual')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('renews_at', models.DateField(blank=True, null=True)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=40)),
                ('discount_pct', models.PositiveSmallIntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=40)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.proprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('open', 'Open'), ('void', 'Void')], default='paid', max_length=10)),
                ('period_label', models.CharField(blank=True, default='', max_length=40)),
                ('issued_at', models.DateField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
