# Generated by Django 5.2.15 on 2026-06-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_stripesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
