# Generated by Django 5.2.15 on 2026-07-15 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_stripesettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Community Monthly'), ('annual', 'Community Annual')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('renews_at', models.DateField(blank=True, null=True)),
                ('past_due_since', models.DateTimeField(blank=True, null=True)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=40)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='stripesettings',
            name='live_price_community_annual',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stripesettings',
            name='live_price_community_monthly',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stripesettings',
            name='test_price_community_annual',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stripesettings',
            name='test_price_community_monthly',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription'),
        ),
    ]
