# Generated by Django 5.2.15 on 2026-07-15 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_communitysubscription_and_more'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysubscription',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='communities.community'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='community_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.communitysubscription'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('community_subscription__isnull', True), ('subscription__isnull', False)), models.Q(('community_subscription__isnull', False), ('subscription__isnull', True)), _connector='OR'), name='billing_invoice_exactly_one_subscription'),
        ),
    ]
