# Generated by Django 5.2.15 on 2026-06-12 19:34

import django.db.models.deletion
import recommendations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_homeownerprofile_avatar_url_proprofile_availability_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_contact', models.CharField(blank=True, default='', max_length=120)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=10)),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('token', models.CharField(default=recommendations.models.generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('hidden', 'Hidden')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.proprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
