# Generated by Django 5.2.15 on 2026-07-16 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_proprofile_communication_quality_pct_and_more'),
        ('leads', '0008_lead_referrer_pro'),
        ('recommendations', '0001_initial'),
        ('referrals', '0016_referrerpro_communication_quality_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='rater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='referrer_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='referrals.referrerpro'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.proprofile'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pro__isnull', False), ('referrer_pro__isnull', True)), models.Q(('pro__isnull', True), ('referrer_pro__isnull', False)), _connector='OR'), name='recommendation_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('pro__isnull', False), ('rater__isnull', False)), fields=('rater', 'pro'), name='unique_rater_pro_rating'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('rater__isnull', False), ('referrer_pro__isnull', False)), fields=('rater', 'referrer_pro'), name='unique_rater_referrer_pro_rating'),
        ),
    ]
