# Generated by Django 5.2.15 on 2026-06-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_homeownerprofile_avatar_url_proprofile_availability_and_more'),
        ('nodes', '0002_node_auto_blast_node_default_sla_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('invoice_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('review_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='krafts', to='nodes.node')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krafts', to='accounts.proprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KraftPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=6)),
                ('image_url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('kraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='krafts.kraft')),
            ],
            options={
                'ordering': ['kind', 'order', 'id'],
            },
        ),
    ]
