# Generated by Django 5.2.15 on 2026-06-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krafts', '0005_backfill_kraft_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kraft',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='kraft',
            name='gig_type',
            field=models.CharField(blank=True, choices=[('under_500', 'Under $500'), ('500_2000', '$500 – $2,000'), ('2000_plus', '$2,000 or more')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kraft',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
    ]
