# Generated by Django 5.2.15 on 2026-06-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_rename_to_prospect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('interested', 'Interested'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('on_hold', 'On Hold'), ('abandoned', 'Abandoned')], default='prospect', max_length=20),
        ),
    ]
