# Generated by Django 5.2.15 on 2026-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_prospect_email_bounced'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='signup_link_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='source',
            field=models.CharField(choices=[('nextdoor', 'Nextdoor'), ('craigslist', 'Craigslist'), ('whatsapp', 'WhatsApp'), ('direct', 'Direct'), ('trade_school', 'Trade School')], default='nextdoor', max_length=20),
        ),
    ]
