# Generated by Django 5.2.15 on 2026-07-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0010_outreachevent'),
        ('vendors', '0010_backfill_prospect_phone_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='propageview',
            name='outreach_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='comms.outreachlog'),
        ),
    ]
