# Generated by Django 5.2.15 on 2026-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sitepageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pros_signup_url_local',
            field=models.URLField(default='http://localhost:5173/for-pros', help_text='Pros signup page URL used in local/dev environment (tracked link redirect target).', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pros_signup_url_prod',
            field=models.URLField(default='https://www.gigkraft.com/for-pros', help_text='Pros signup page URL used in production (tracked link redirect target).', max_length=500),
        ),
    ]
