# Generated by Django 5.2.15 on 2026-06-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_quoterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='budget',
            field=models.CharField(choices=[('no_pref', 'No preference'), ('under_500', 'Under $500'), ('500_2k', '$500–$2k'), ('2k_10k', '$2k–$10k'), ('over_10k', '$10k+')], default='no_pref', max_length=20),
        ),
    ]
