# Generated by Django 5.2.15 on 2026-07-15 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_zipwaitlistentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text="Non-pro recipient (e.g. a Community owner) for threads that aren't pro-directed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
