# Generated by Django 5.2.15 on 2026-07-16 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_recipient'),
        ('referrals', '0016_referrerpro_communication_quality_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referrer_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_leads', to='referrals.referrerpro'),
        ),
    ]
