# Generated by Django 5.2.15 on 2026-07-15 03:10

import django.db.models.deletion
import referrals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0006_zipwaitlistentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('slug_locked', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('cover_image_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived (voluntary downgrade — read-only forever)')], default='active', max_length=10)),
                ('short_code', models.CharField(blank=True, db_index=True, default='', max_length=10, unique=True)),
                ('short_link_click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(limit_choices_to={'role__in': ['referrer', 'community_lead', 'homeowner']}, on_delete=django.db.models.deletion.CASCADE, related_name='community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='communities.community')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_referral', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('request_submitted', 'Request Submitted'), ('member_joined', 'Member Joined')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='communities.community')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['community', 'event_type', 'created_at'], name='communities_communi_cab393_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('declined', 'Declined')], default='invited', max_length=10)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator')], default='member', max_length=10)),
                ('token', models.CharField(db_index=True, default=referrals.models._generate_token, max_length=64, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('otp_code_hash', models.CharField(blank=True, default='', max_length=64)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('last_resent_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('community', 'phone'), name='unique_community_member_phone'), models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('community', 'email'), name='unique_community_member_email')],
            },
        ),
    ]
