# Generated by Django 5.2.15 on 2026-07-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='slug_locked',
        ),
    ]
