# Generated by Django 5.2.15 on 2026-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_remove_community_slug_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
