# Generated by Django 5.2.15 on 2026-07-15 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='communitymember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('community', 'user'), name='unique_community_member_user'),
        ),
    ]
