# Generated by Django 5.2.15 on 2026-07-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_communitymember_unique_community_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityanalyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('request_submitted', 'Request Submitted'), ('member_joined', 'Member Joined'), ('owner_message_anon', 'Anonymous Message to Owner')], max_length=20),
        ),
    ]
