# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_communityanalyticsevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityanalyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('request_submitted', 'Request Submitted'), ('member_joined', 'Member Joined'), ('owner_message_anon', 'Anonymous Message to Owner'), ('link_copied', 'Page Link Copied')], max_length=20),
        ),
    ]
