# Generated by Django 5.2.15 on 2026-07-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_communityanalyticsevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('pending', 'Pending Approval'), ('joined', 'Joined'), ('declined', 'Declined')], default='invited', max_length=10),
        ),
    ]
